CREATE TABLE `sheet` (
  `id` VARCHAR(32) NOT NULL,
  `race` VARCHAR(50) NULL,
  `name` VARCHAR(50) NULL,
  `class` VARCHAR(50) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

ALTER TABLE `sheet` ADD COLUMN `share_token` VARCHAR(40) NULL;

ALTER TABLE `sheet` ADD COLUMN `level` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `int` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `int_mod` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `int_saving_throw` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `wis` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `wis_mod` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `wis_saving_throw` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `char` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `char_mod` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `char_saving_throw` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `str` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `str_mod` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `str_saving_throw` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `dex` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `dex_mod` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `dex_saving_throw` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `con` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `con_mod` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `con_saving_throw` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `hp_max` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `hp_cur` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `hp_tmp` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `hit_die` VARCHAR(5) NULL;
ALTER TABLE `sheet` ADD COLUMN `armor_class` INTEGER NULL;
ALTER TABLE `sheet` ADD COLUMN `initiative` VARCHAR(3) NULL;
ALTER TABLE `sheet` ADD COLUMN `speed` INTEGER NULL;
