name: Run Production Tests

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_prod_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
        if_key_exists: ignore
    - name: Run tests
      run: ssh whatthesheet@whatthesheet.app "cd /web/whatthesheet && /usr/local/bin/composer test"; exit 1;
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ job.status }} @ ${{ github.job }} in ${{ github.repository }}
        body: "Job: ${{ github.job }}\nWorkflow: ${{ github.workflow }}\nRepo link: https://github.com/${{ github.repository }}\nStatus: ${{ job.status }}"
        to: ${{ secrets.EMAIL_USERNAME }}
        from: Tim The Git <${{ secrets.EMAIL_USERNAME }}>
