name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
        if_key_exists: ignore
    - name: Pull
      run: ssh whatthesheet@whatthesheet.app "cd /web/whatthesheet && /usr/bin/git pull"

    - name: Update dependencies
      run: ssh whatthesheet@whatthesheet.app "cd /web/whatthesheet && /usr/local/bin/composer install --no-dev"

    - name: Migrate up
      run: ssh whatthesheet@whatthesheet.app "cd /web/whatthesheet && /usr/local/bin/composer run-script migrate-up"

    - name: Run tests
      run: ssh whatthesheet@whatthesheet.app "cd /web/whatthesheet && /usr/local/bin/composer test"

    - name: Clear cache
      run: ssh whatthesheet@whatthesheet.app "sudo varnishadm -S /etc/varnish/secret -T 127.0.0.1:6082 \"ban req.http.host == whatthesheet.app\""
