name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.SSH_KNOWN_HOST }}
        if_key_exists: ignore
    - name: Pull
      run: ssh whatthesheet@whatthesheet.app "cd /web/whatthesheet && /usr/bin/git pull"
